### ISSUE TITLE
Add babel-plugin-module-resolver for the src/ folder

### ISSUE THREAD

**Issue by snags88** [curology/radiance-ui#34]
A lot of the files inside of the src folder are using relative paths and when things are deeply nested, it gets too crazy. We can get around that by using [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver)

**Comment by michaeljaltamirano** [comment]
Closing, no longer applies and for our TypeScript types to work correctly we need to use relative import paths.
